#ifndef OPENDSPX_SERIALIZER_OPENDSPXSERIALIZERGLOBAL_H
#define OPENDSPX_SERIALIZER_OPENDSPXSERIALIZERGLOBAL_H

#include <stdcorelib/stdc_global.h>

#ifndef OPENDSPX_SERIALIZER_EXPORT
#  ifdef OPENDSPX_SERIALIZER_STATIC
#    define OPENDSPX_SERIALIZER_EXPORT
#  else
#    ifdef OPENDSPX_SERIALIZER_LIBRARY
#      define OPENDSPX_SERIALIZER_EXPORT STDCORELIB_DECL_EXPORT
#    else
#      define OPENDSPX_SERIALIZER_EXPORT STDCORELIB_DECL_IMPORT
#    endif
#  endif
#endif

#endif //OPENDSPX_SERIALIZER_OPENDSPXSERIALIZERGLOBAL_H
